---
gathering: smart

# Installation folders
install_temp_dir: /tmp/ansible-install
install_dir: /opt

spark:
  version: 2.4.5
  hadoop_version: 2.7
  working_dir: /tmp/spark/data
  events_dir: /tmp/spark-events
  log_dir: /var/log/spark
  master_port: 7077
  worker_work_port: 65000
  master_ui_port: 8080
  worker_ui_port: 8085
  worker_instances: 1
  download_location: https://pub.tutosfaciles48.fr/mirrors/apache/spark
  user: "spark"               # the name of the (OS)user created for spark
  user_groups: []             # Optional list of (OS)groups the new spark user should belong to
  user_shell: "/bin/bash"

  env_extras: {}
  defaults_extras: {
    spark.master: "spark://{{ hostvars['master']['ansible_host'] }}:7077",
    spark.eventLog.enabled: true
  }

livy:
  version: 0.7.0
  log_dir: /var/log/livy
  download_location: https://mirror.ibcp.fr/pub/apache/incubator/livy/
  user: "spark"