---

- name: update spark configuration 'spark-env.sh'
  template:
    src: "livy-env.sh.j2"
    dest: "{{ livy_home }}/conf/livy-env.sh"
  tags: livy_conf
  notify: restart_livy


- name: Create livy log directory
  file:
    path: "{{ livy.log_dir }}"
    state: directory
    owner: "{{ livy.user }}"
    group: "{{ livy.user }}"
  become: true
  notify: restart_livy